/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.hotel.rec.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RecServiceType implements org.apache.thrift.TEnum {
  SELECT_REC(0),
  SEARCH_REC(1),
  POI_DETAIL_REC(2),
  CROSS_REC(3),
  REC_PREORDER_POI(4),
  REC_VACATION_POI(5);

  private final int value;

  private RecServiceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RecServiceType findByValue(int value) { 
    switch (value) {
      case 0:
        return SELECT_REC;
      case 1:
        return SEARCH_REC;
      case 2:
        return POI_DETAIL_REC;
      case 3:
        return CROSS_REC;
      case 4:
        return REC_PREORDER_POI;
      case 5:
        return REC_VACATION_POI;
      default:
        return null;
    }
  }
}
