/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.hotel.rec.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SortingMethod implements org.apache.thrift.TEnum {
  SMART(0),
  DISTANCE(1),
  SOLD(2),
  AVG_SCORE(3),
  LOWEST_PRICE(4),
  HIGH_PRICE(5);

  private final int value;

  private SortingMethod(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SortingMethod findByValue(int value) { 
    switch (value) {
      case 0:
        return SMART;
      case 1:
        return DISTANCE;
      case 2:
        return SOLD;
      case 3:
        return AVG_SCORE;
      case 4:
        return LOWEST_PRICE;
      case 5:
        return HIGH_PRICE;
      default:
        return null;
    }
  }
}
