/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.hotel.search.recommend;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PoiResponseStatus implements org.apache.thrift.TEnum {
  OK(0),
  ERROR(1);

  private final int value;

  private PoiResponseStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PoiResponseStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return ERROR;
      default:
        return null;
    }
  }
}
