/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.hotel.search.recommend;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PoiSearchSource implements org.apache.thrift.TEnum {
  DEFAULT(0),
  HOTEL(1),
  MERGESERVER(2);

  private final int value;

  private PoiSearchSource(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PoiSearchSource findByValue(int value) { 
    switch (value) {
      case 0:
        return DEFAULT;
      case 1:
        return HOTEL;
      case 2:
        return MERGESERVER;
      default:
        return null;
    }
  }
}
