/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.hotel.rec.cross;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RecSceneTypeEnum implements org.apache.thrift.TEnum {
  TRAFFIC_DEPART_HOTEL(1),
  TRAFFIC_DEPART_TRAVEL(2),
  TRAFFIC_DEST_HOTEL(3),
  TRAFFIC_DEST_TRAVEL(4),
  HOTEL_DEST_TRAVEL(5),
  HOTEL_GPS_TRAVEL(6),
  HOTEL_NEARBY_TRAVEL(7),
  TRAVEL_DEST_HOTEL(8),
  TRAVEL_DEST_TRAVEL(9),
  TRAVEL_GPS_HOTEL(10),
  TRAVEL_GPS_TRAVEL(11),
  TRAVEL_NEARBY_HOTEL(12),
  TRAVEL_NEARBY_TRAVEL(13);

  private final int value;

  private RecSceneTypeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RecSceneTypeEnum findByValue(int value) { 
    switch (value) {
      case 1:
        return TRAFFIC_DEPART_HOTEL;
      case 2:
        return TRAFFIC_DEPART_TRAVEL;
      case 3:
        return TRAFFIC_DEST_HOTEL;
      case 4:
        return TRAFFIC_DEST_TRAVEL;
      case 5:
        return HOTEL_DEST_TRAVEL;
      case 6:
        return HOTEL_GPS_TRAVEL;
      case 7:
        return HOTEL_NEARBY_TRAVEL;
      case 8:
        return TRAVEL_DEST_HOTEL;
      case 9:
        return TRAVEL_DEST_TRAVEL;
      case 10:
        return TRAVEL_GPS_HOTEL;
      case 11:
        return TRAVEL_GPS_TRAVEL;
      case 12:
        return TRAVEL_NEARBY_HOTEL;
      case 13:
        return TRAVEL_NEARBY_TRAVEL;
      default:
        return null;
    }
  }
}
